{"uid":"4b4757e66a1912dae1a509f688f20b0f","name":"categories","children":[{"name":"Product defects","children":[{"name":"assert 0 == 1\n +  where 0 = len(<ixnetwork_restpy.testplatform.sessions.ixnetwork.availablehardware.chassis.chassis.Chassis object at 0x7f1eec64eac0>)","children":[{"name":"test_counter_ip_dscp","uid":"9da65f76426b628c","parentUid":"29864539130d556caf6b8e9bd9a331f6","status":"failed","time":{"start":1743703353732,"stop":1743703375421,"duration":21689},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"29864539130d556caf6b8e9bd9a331f6"},{"name":"snappi_ixnetwork.exceptions.SnappiIxnException:   File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/snappi_api.py\", line 276, in set_config\n    self.config_ixnetwork(config)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/snappi_api.py\", line 364, in config_ixnetwork\n    self.traffic_item.config()\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/trafficitem.py\", line 773, in config\n    ixn_traffic_item = self.get_ixn_config(self._config)[0]\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/trafficitem.py\", line 536, in get_ixn_config\n    self._importconfig(imports)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/trafficitem.py\", line 464, in _importconfig\n    raise SnappiIxnException(\n [{'xpath': '', 'message': 'Object reference not set to an instance of an object.', 'severity': 'kError', 'category': 'invalidCommit', 'property': 'noAtt'}, {'xpath': '', 'message': 'Object reference not set to an instance of an object.', 'severity': 'kError', 'category': 'invalidCommit', 'property': 'noAtt'}]","children":[{"name":"test_static_and_lacp_lag","uid":"ae8d8f99db8cd34d","parentUid":"490ae52d42d20191af93b453f2ce50f5","status":"failed","time":{"start":1743703353732,"stop":1743703400455,"duration":46723},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_static_lag","uid":"530527175e1d3d83","parentUid":"490ae52d42d20191af93b453f2ce50f5","status":"failed","time":{"start":1743703353732,"stop":1743703444507,"duration":90775},"flaky":true,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_phb_ecn","uid":"a3dba05a89021e3c","parentUid":"490ae52d42d20191af93b453f2ce50f5","status":"failed","time":{"start":1743703353732,"stop":1743703473933,"duration":120201},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"490ae52d42d20191af93b453f2ce50f5"},{"name":"assert 400 == 500","children":[{"name":"test_device_connection","uid":"11ef772f3aa86af7","parentUid":"5dc59fb3fa66403244a17904c0e00b01","status":"failed","time":{"start":1743703353732,"stop":1743703415372,"duration":61640},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"5dc59fb3fa66403244a17904c0e00b01"},{"name":"snappi_ixnetwork.exceptions.SnappiIxnException:   File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/snappi_api.py\", line 450, in set_control_state\n    self.traffic_item.transmit(request_payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/trafficitem.py\", line 1321, in transmit\n    self._api._traffic.Apply()\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/testplatform/sessions/ixnetwork/traffic/traffic.py\", line 1395, in Apply\n    return self._execute(\"apply\", payload=payload, response_object=None)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/base.py\", line 452, in _execute\n    response = self._connection._execute(url, payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 289, in _execute\n    return self._send_recv(\"POST\", url, payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 572, in _send_recv\n    return self._poll()\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 640, in _poll\n    return self._process_response_status_code(\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 476, in _process_response_status_code\n    raise BadRequestError(message, response.status_code)\n  Error in L2/L3 Traffic Apply","children":[{"name":"test_latency_metrics","uid":"528d302f972dae8e","parentUid":"b56ca0ff9daa8a9941dfbaa2977c5e56","status":"failed","time":{"start":1743703353732,"stop":1743703393959,"duration":40227},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_list_tcp_ports_e2e","uid":"fad42c84b15cfe43","parentUid":"b56ca0ff9daa8a9941dfbaa2977c5e56","status":"failed","time":{"start":1743703353732,"stop":1743703441023,"duration":87291},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_stats_filter","uid":"29b1ca6219cd4cbf","parentUid":"b56ca0ff9daa8a9941dfbaa2977c5e56","status":"failed","time":{"start":1743703353732,"stop":1743703437876,"duration":84144},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_update_flows","uid":"48ed4f539bc14b9d","parentUid":"b56ca0ff9daa8a9941dfbaa2977c5e56","status":"failed","time":{"start":1743703353732,"stop":1743703397955,"duration":44223},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_only_config","uid":"5a6b6e5d6ee30974","parentUid":"b56ca0ff9daa8a9941dfbaa2977c5e56","status":"failed","time":{"start":1743703353732,"stop":1743703398070,"duration":44338},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_list_tcp_ports_e2e","uid":"314b16585ac0882e","parentUid":"b56ca0ff9daa8a9941dfbaa2977c5e56","status":"failed","time":{"start":1743703353732,"stop":1743703436835,"duration":83103},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"b56ca0ff9daa8a9941dfbaa2977c5e56"},{"name":"snappi_ixnetwork.exceptions.SnappiIxnException: IxNet - Failure message received from Interface Manager on port novus1-715849.ccu.is.keysight.com;1;2: unknown-error - Could not load plugin cpf: static ixePlugin* ixePlugin::LoadPlugin(const string&, const string&): dlopen: /usr/lib/ixe/plugins/libcpf.so: undefined symbol: _ZNK7DataSeq8IMPlugin33localTimestampMilliImplementationEv.","children":[{"name":"test_encrypt_with_mka","uid":"4aecba204eb13c99","parentUid":"47595611af44296a1f58f1ac5c4b6caf","status":"failed","time":{"start":1743703353732,"stop":1743703463912,"duration":110180},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_encrypt","uid":"42aa429187a04bb","parentUid":"47595611af44296a1f58f1ac5c4b6caf","status":"failed","time":{"start":1743703353732,"stop":1743703428030,"duration":74298},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"47595611af44296a1f58f1ac5c4b6caf"},{"name":"snappi_ixnetwork.exceptions.SnappiIxnException: IxNet - Failure message received from Interface Manager on port novus1-715849.ccu.is.keysight.com;1;1: unknown-error - Could not load plugin cpf: static ixePlugin* ixePlugin::LoadPlugin(const string&, const string&): dlopen: /usr/lib/ixe/plugins/libcpf.so: undefined symbol: _ZNK7DataSeq8IMPlugin33localTimestampMilliImplementationEv.","children":[{"name":"test_compact","uid":"23ab2bba011c80f3","parentUid":"da9649f3b36a8ed1237d626e3b1f8f77","status":"failed","time":{"start":1743703353732,"stop":1743703386991,"duration":33259},"flaky":true,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_manual_gateway_mac","uid":"5c5a2038458f419d","parentUid":"da9649f3b36a8ed1237d626e3b1f8f77","status":"failed","time":{"start":1743703353732,"stop":1743703418434,"duration":64702},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_mka_stats","uid":"625c34276c37469d","parentUid":"da9649f3b36a8ed1237d626e3b1f8f77","status":"failed","time":{"start":1743703353732,"stop":1743703439462,"duration":85730},"flaky":true,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"da9649f3b36a8ed1237d626e3b1f8f77"},{"name":"snappi_ixnetwork.exceptions.SnappiIxnException:   File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/snappi_api.py\", line 433, in set_control_state\n    self.capture.set_capture_state(request_payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/capture.py\", line 495, in set_capture_state\n    self._start_capture()\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/capture.py\", line 524, in _start_capture\n    self._api._ixnetwork.StartCapture()\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/testplatform/sessions/ixnetwork/ixnetwork.py\", line 2884, in StartCapture\n    return self._execute(\"startCapture\", payload=payload, response_object=None)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/base.py\", line 452, in _execute\n    response = self._connection._execute(url, payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 289, in _execute\n    return self._send_recv(\"POST\", url, payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 572, in _send_recv\n    return self._poll()\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 640, in _poll\n    return self._process_response_status_code(\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 476, in _process_response_status_code\n    raise BadRequestError(message, response.status_code)\n  The capture can't be started on a virtual port.","children":[{"name":"test_traffic_gptv_config","uid":"ab8c6ea67c150a28","parentUid":"925eb53b702459181baa2d0323af853d","status":"failed","time":{"start":1743703353732,"stop":1743703370741,"duration":17009},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_traffic_ethernet_pause","uid":"7b46993746b36786","parentUid":"925eb53b702459181baa2d0323af853d","status":"failed","time":{"start":1743703353732,"stop":1743703370104,"duration":16372},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_traffic_transmit_state","uid":"bc8e5a9f13eb0ad8","parentUid":"925eb53b702459181baa2d0323af853d","status":"failed","time":{"start":1743703353732,"stop":1743703370774,"duration":17042},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_udp_header_with_fixed_length_checksum_e2e","uid":"926a6ead499b6f47","parentUid":"925eb53b702459181baa2d0323af853d","status":"failed","time":{"start":1743703353732,"stop":1743703370726,"duration":16994},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_udp_header_with_counter_e2e","uid":"90a6faf8ed8cf873","parentUid":"925eb53b702459181baa2d0323af853d","status":"failed","time":{"start":1743703353732,"stop":1743703426695,"duration":72963},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_traffic_custom_header","uid":"80167770edb234a8","parentUid":"925eb53b702459181baa2d0323af853d","status":"failed","time":{"start":1743703353732,"stop":1743703369756,"duration":16024},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_udp_header_with_list_e2e","uid":"b068dc9adbe479fb","parentUid":"925eb53b702459181baa2d0323af853d","status":"failed","time":{"start":1743703353732,"stop":1743703423833,"duration":70101},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"925eb53b702459181baa2d0323af853d"},{"name":"snappi_ixnetwork.exceptions.SnappiIxnException:   File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/snappi_api.py\", line 561, in get_metrics\n    response = self.traffic_item.results(request.flow)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/trafficitem.py\", line 1500, in results\n    ).Page\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/testplatform/sessions/ixnetwork/statistics/view/view.py\", line 554, in Page\n    return Page(self)._select()\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/base.py\", line 548, in _select\n    end = len(self._parent.href)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/base.py\", line 158, in href\n    return self._get_attribute(\"href\")\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/base.py\", line 218, in _get_attribute\n    raise NotFoundError(msg)\n Failed to get the View.href property as the View object has no encapsulated resources. Either the View.find() method was not called or it failed to retrieve any resources from the server.","children":[{"name":"test_only_metrics","uid":"3b0a0f2d5a2fd03e","parentUid":"a67e6bb59544e30bacf9972500e5a0fb","status":"failed","time":{"start":1743703353732,"stop":1743703355496,"duration":1764},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"a67e6bb59544e30bacf9972500e5a0fb"},{"name":"snappi_ixnetwork.exceptions.SnappiIxnException:   File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/snappi_api.py\", line 276, in set_config\n    self.config_ixnetwork(config)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/snappi_api.py\", line 374, in config_ixnetwork\n    self._ixnetwork.StartAllProtocols()\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/testplatform/sessions/ixnetwork/ixnetwork.py\", line 2862, in StartAllProtocols\n    return self._execute(\"startAllProtocols\", payload=payload, response_object=None)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/base.py\", line 452, in _execute\n    response = self._connection._execute(url, payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 289, in _execute\n    return self._send_recv(\"POST\", url, payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 572, in _send_recv\n    return self._poll()\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 640, in _poll\n    return self._process_response_status_code(\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 476, in _process_response_status_code\n    raise BadRequestError(message, response.status_code)\n  Failure message received from Interface Manager on port novus1-715849.ccu.is.keysight.com;1;1: unknown-error - Could not load plugin cpf: static ixePlugin* ixePlugin::LoadPlugin(const string&, const string&): dlopen: /usr/lib/ixe/plugins/libcpf.so: undefined symbol: _ZNK7DataSeq8IMPlugin33localTimestampMilliImplementationEv.\nSystem Exception Caught. Exception Text: Failure message received from Interface Manager on port novus1-715849.ccu.is.keysight.com;1;1: unknown-error - Could not load plugin cpf: static ixePlugin* ixePlugin::LoadPlugin(const string&, const string&): dlopen: /usr/lib/ixe/plugins/libcpf.so: undefined symbol: _ZNK7DataSeq8IMPlugin33localTimestampMilliImplementationEv.","children":[{"name":"test_traffic","uid":"a8cf24d4348e099","parentUid":"b13feb8405b4b7613e3792c68aaf5e52","status":"failed","time":{"start":1743703353732,"stop":1743703371191,"duration":17459},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_device_lag_name","uid":"d0923fa895735c41","parentUid":"b13feb8405b4b7613e3792c68aaf5e52","status":"failed","time":{"start":1743703353732,"stop":1743703430299,"duration":76567},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_flow_tracking_stats","uid":"bcfd1410ea93ba3e","parentUid":"b13feb8405b4b7613e3792c68aaf5e52","status":"failed","time":{"start":1743703353732,"stop":1743703400041,"duration":46309},"flaky":true,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_ping","uid":"80377aec13a118d0","parentUid":"b13feb8405b4b7613e3792c68aaf5e52","status":"failed","time":{"start":1743703353732,"stop":1743703371528,"duration":17796},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_lacp_lag","uid":"4435106b5110ffc0","parentUid":"b13feb8405b4b7613e3792c68aaf5e52","status":"failed","time":{"start":1743703353732,"stop":1743703400434,"duration":46702},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"b13feb8405b4b7613e3792c68aaf5e52"},{"name":"snappi_ixnetwork.exceptions.SnappiIxnException:   File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/snappi_api.py\", line 442, in set_control_state\n    self.ngpf.set_protocol_state(request_payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/device/ngpf.py\", line 256, in set_protocol_state\n    self.api._ixnetwork.StartAllProtocols(\"sync\")\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/testplatform/sessions/ixnetwork/ixnetwork.py\", line 2862, in StartAllProtocols\n    return self._execute(\"startAllProtocols\", payload=payload, response_object=None)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/base.py\", line 452, in _execute\n    response = self._connection._execute(url, payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 289, in _execute\n    return self._send_recv(\"POST\", url, payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 572, in _send_recv\n    return self._poll()\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 640, in _poll\n    return self._process_response_status_code(\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 476, in _process_response_status_code\n    raise BadRequestError(message, response.status_code)\n  Failure message received from Interface Manager on port novus1-715849.ccu.is.keysight.com;1;1: unknown-error - Could not load plugin cpf: static ixePlugin* ixePlugin::LoadPlugin(const string&, const string&): dlopen: /usr/lib/ixe/plugins/libcpf.so: undefined symbol: _ZNK7DataSeq8IMPlugin33localTimestampMilliImplementationEv.\nSystem Exception Caught. Exception Text: Failure message received from Interface Manager on port novus1-715849.ccu.is.keysight.com;1;1: unknown-error - Could not load plugin cpf: static ixePlugin* ixePlugin::LoadPlugin(const string&, const string&): dlopen: /usr/lib/ixe/plugins/libcpf.so: undefined symbol: _ZNK7DataSeq8IMPlugin33localTimestampMilliImplementationEv.","children":[{"name":"test_vxlan_b2b","uid":"6800ac3adc4a5e69","parentUid":"b5a7ae18b8ccdbf8b9a3b24dbf0951a7","status":"failed","time":{"start":1743703353732,"stop":1743703415472,"duration":61740},"flaky":true,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_bgpv6_routes","uid":"88143e874e4ede6","parentUid":"b5a7ae18b8ccdbf8b9a3b24dbf0951a7","status":"failed","time":{"start":1743703353732,"stop":1743703428768,"duration":75036},"flaky":true,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"b5a7ae18b8ccdbf8b9a3b24dbf0951a7"},{"name":"snappi_ixnetwork.exceptions.SnappiIxnException:   File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/snappi_api.py\", line 276, in set_config\n    self.config_ixnetwork(config)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/snappi_api.py\", line 374, in config_ixnetwork\n    self._ixnetwork.StartAllProtocols()\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/testplatform/sessions/ixnetwork/ixnetwork.py\", line 2862, in StartAllProtocols\n    return self._execute(\"startAllProtocols\", payload=payload, response_object=None)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/base.py\", line 452, in _execute\n    response = self._connection._execute(url, payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 289, in _execute\n    return self._send_recv(\"POST\", url, payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 572, in _send_recv\n    return self._poll()\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 640, in _poll\n    return self._process_response_status_code(\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 476, in _process_response_status_code\n    raise BadRequestError(message, response.status_code)\n  Failure message received from Interface Manager on port novus1-715849.ccu.is.keysight.com;1;1: unknown-error - Could not load plugin cpf: static ixePlugin* ixePlugin::LoadPlugin(const string&, const string&): dlopen: /usr/lib/ixe/plugins/libcpf.so: undefined symbol: _ZNK7DataSeq8IMPlugin33localTimestampMilliImplementationEv.","children":[{"name":"test_port_name","uid":"5f81b468359d0c00","parentUid":"3944caaf140ae18e2d820e4e4382219e","status":"failed","time":{"start":1743703353732,"stop":1743703359515,"duration":5783},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_connection_portname","uid":"f9269763e97bac70","parentUid":"3944caaf140ae18e2d820e4e4382219e","status":"failed","time":{"start":1743703353732,"stop":1743703359374,"duration":5642},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]},{"name":"test_ping_cvg","uid":"db4752ea5cbdd6b5","parentUid":"3944caaf140ae18e2d820e4e4382219e","status":"failed","time":{"start":1743703353732,"stop":1743703360991,"duration":7259},"flaky":true,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"3944caaf140ae18e2d820e4e4382219e"},{"name":"Exception: Time out occurred while waiting for stats to be as expected","children":[{"name":"test_encrypt_with_mka_multiple_devices","uid":"fa878ee80a56a0eb","parentUid":"3596725c47ed555d65da3fbf3423e1cd","status":"failed","time":{"start":1743703353732,"stop":1743703472657,"duration":118925},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"3596725c47ed555d65da3fbf3423e1cd"},{"name":"snappi_ixnetwork.exceptions.SnappiIxnException:   File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/snappi_api.py\", line 442, in set_control_state\n    self.ngpf.set_protocol_state(request_payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/snappi_ixnetwork/device/ngpf.py\", line 256, in set_protocol_state\n    self.api._ixnetwork.StartAllProtocols(\"sync\")\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/testplatform/sessions/ixnetwork/ixnetwork.py\", line 2862, in StartAllProtocols\n    return self._execute(\"startAllProtocols\", payload=payload, response_object=None)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/base.py\", line 452, in _execute\n    response = self._connection._execute(url, payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 289, in _execute\n    return self._send_recv(\"POST\", url, payload)\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 572, in _send_recv\n    return self._poll()\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 640, in _poll\n    return self._process_response_status_code(\n  File \"/home/github-runner/actions-runner/_work/snappi-ixnetwork/snappi-ixnetwork/.env/lib/python3.10/site-packages/ixnetwork_restpy/connection.py\", line 476, in _process_response_status_code\n    raise BadRequestError(message, response.status_code)\n  Failure message received from Interface Manager on port novus1-715849.ccu.is.keysight.com;1;1: unknown-error - Could not load plugin cpf: static ixePlugin* ixePlugin::LoadPlugin(const string&, const string&): dlopen: /usr/lib/ixe/plugins/libcpf.so: undefined symbol: _ZNK7DataSeq8IMPlugin33localTimestampMilliImplementationEv.","children":[{"name":"test_vxlan_b2b_v6","uid":"4560df9cfd1a73e","parentUid":"73ed35dc3b9f73ed3ec5717b9c1cad1f","status":"failed","time":{"start":1743703353732,"stop":1743703364318,"duration":10586},"flaky":true,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"73ed35dc3b9f73ed3ec5717b9c1cad1f"}],"uid":"8fb3a91ba5aaf9de24cc8a92edc82b5d"}]}